# Generated by Django 6.0.5 on 2026-05-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='course_type',
            new_name='courseType',
        ),
    ]
