# Generated by Django 6.0.5 on 2026-05-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
